image: node:latest

# CI for frontend, built in Yarn.
stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags: 
    - docker
  script:
    - npm i -g yarn
    - yarn
    - yarn build
